// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hw.proto

/*
Package message is a generated protocol buffer package.

It is generated from these files:
	hw.proto

It has these top-level messages:
	HelloRequest
	HelloReply
	ByeRequest
	ByeReply
*/
package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type HelloRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *HelloRequest) Reset()                    { *m = HelloRequest{} }
func (m *HelloRequest) String() string            { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()               {}
func (*HelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *HelloReply) Reset()                    { *m = HelloReply{} }
func (m *HelloReply) String() string            { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()               {}
func (*HelloReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// The request message containing the user's name.
type ByeRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *ByeRequest) Reset()                    { *m = ByeRequest{} }
func (m *ByeRequest) String() string            { return proto.CompactTextString(m) }
func (*ByeRequest) ProtoMessage()               {}
func (*ByeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ByeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings
type ByeReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *ByeReply) Reset()                    { *m = ByeReply{} }
func (m *ByeReply) String() string            { return proto.CompactTextString(m) }
func (*ByeReply) ProtoMessage()               {}
func (*ByeReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ByeReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "message.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "message.HelloReply")
	proto.RegisterType((*ByeRequest)(nil), "message.ByeRequest")
	proto.RegisterType((*ByeReply)(nil), "message.ByeReply")
}

func init() { proto.RegisterFile("hw.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 156 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc8, 0x28, 0xd7, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x55, 0x52, 0xe2,
	0xe2, 0xf1, 0x48, 0xcd, 0xc9, 0xc9, 0x0f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe2,
	0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x95, 0xd4,
	0xb8, 0xb8, 0xa0, 0x6a, 0x0a, 0x72, 0x2a, 0x85, 0x24, 0xb8, 0x60, 0x9a, 0xa1, 0x8a, 0xe0, 0x66,
	0x29, 0x70, 0x71, 0x39, 0x55, 0xa6, 0xe2, 0x33, 0x49, 0x85, 0x8b, 0x03, 0xac, 0x02, 0xaf, 0x39,
	0x4e, 0x06, 0x5c, 0xd2, 0x99, 0xf9, 0x7a, 0xe9, 0x45, 0x05, 0xc9, 0x7a, 0xa9, 0x15, 0x89, 0xb9,
	0x05, 0x39, 0xa9, 0xc5, 0x7a, 0x19, 0x20, 0x07, 0x94, 0xe7, 0x17, 0xe5, 0xa4, 0x38, 0xf1, 0x83,
	0x1d, 0x13, 0x0e, 0x62, 0x07, 0x80, 0x3c, 0x13, 0xc0, 0x98, 0xc4, 0x06, 0xf6, 0x95, 0x31, 0x20,
	0x00, 0x00, 0xff, 0xff, 0x79, 0xe1, 0x00, 0xa9, 0xe1, 0x00, 0x00, 0x00,
}
