// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service/helloworld.proto

/*
Package service is a generated protocol buffer package.

It is generated from these files:
	service/helloworld.proto

It has these top-level messages:
*/
package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import message "message"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Greeter service

type GreeterClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *message.HelloRequest, opts ...grpc.CallOption) (*message.HelloReply, error)
	SayBye(ctx context.Context, in *message.ByeRequest, opts ...grpc.CallOption) (*message.ByeReply, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *message.HelloRequest, opts ...grpc.CallOption) (*message.HelloReply, error) {
	out := new(message.HelloReply)
	err := grpc.Invoke(ctx, "/service.Greeter/SayHello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) SayBye(ctx context.Context, in *message.ByeRequest, opts ...grpc.CallOption) (*message.ByeReply, error) {
	out := new(message.ByeReply)
	err := grpc.Invoke(ctx, "/service.Greeter/SayBye", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Greeter service

type GreeterServer interface {
	// Sends a greeting
	SayHello(context.Context, *message.HelloRequest) (*message.HelloReply, error)
	SayBye(context.Context, *message.ByeRequest) (*message.ByeReply, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(message.HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*message.HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_SayBye_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(message.ByeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayBye(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Greeter/SayBye",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayBye(ctx, req.(*message.ByeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
		{
			MethodName: "SayBye",
			Handler:    _Greeter_SayBye_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service/helloworld.proto",
}

func init() { proto.RegisterFile("service/helloworld.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 179 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x28, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0xcf, 0x48, 0xcd, 0xc9, 0xc9, 0x2f, 0xcf, 0x2f, 0xca, 0x49, 0xd1, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0xca, 0x48, 0x09, 0xe4, 0xa6, 0x16, 0x17, 0x27, 0xa6,
	0xa7, 0xea, 0x67, 0x94, 0x43, 0xa4, 0x8c, 0xca, 0xb9, 0xd8, 0xdd, 0x8b, 0x52, 0x53, 0x4b, 0x52,
	0x8b, 0x84, 0x2c, 0xb8, 0x38, 0x82, 0x13, 0x2b, 0x3d, 0x40, 0x9a, 0x85, 0x44, 0xf5, 0xa0, 0x2a,
	0xf5, 0xc0, 0xfc, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x29, 0x61, 0x74, 0xe1, 0x82, 0x9c,
	0x4a, 0x25, 0x06, 0x21, 0x23, 0x2e, 0xb6, 0xe0, 0xc4, 0x4a, 0xa7, 0xca, 0x54, 0x21, 0x84, 0x02,
	0xa7, 0xca, 0x54, 0x98, 0x2e, 0x41, 0x54, 0x41, 0xb0, 0x1e, 0x27, 0x4b, 0x2e, 0xe9, 0xcc, 0x7c,
	0xbd, 0xf4, 0xa2, 0x82, 0x64, 0xbd, 0xd4, 0x8a, 0xc4, 0xdc, 0x82, 0x9c, 0xd4, 0x62, 0x3d, 0x84,
	0xc3, 0x9d, 0xf8, 0xc1, 0x16, 0x84, 0x83, 0xd8, 0x01, 0x20, 0x87, 0x06, 0x30, 0x46, 0xc1, 0x7c,
	0x91, 0xc4, 0x06, 0x76, 0xba, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x20, 0x5a, 0xf2, 0x69, 0xf1,
	0x00, 0x00, 0x00,
}
